version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo

    depends_on:
          - "mongo"


  finquest_api:
    # image: finquest:latest
    ports:
      - 8081:80
    build:
      context: ./FinquestTest
      dockerfile: Dockerfile

  writerservice:
    # image: writerservice:latest
    depends_on:
      - "finquest_api"
    build:
      context: ./WriterService
      dockerfile: Dockerfile
    environment:
      WEBSITE_URL: http://finquest_api-dev