version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo

    depends_on:
          - "mongo"
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"


  finquest_api:
    # image: finquest:latest
    ports:
      - 8083:80
    build:
      context: ./FinquestTest
      dockerfile: Dockerfile
    depends_on:
      - "rabbitmq"
      # rabbitmq:
      #   condition: service_started

  writerservice:
    # image: writerservice:latest
    depends_on:
      - "finquest_api"
      # finquest_api:
      #   condition: service_started

    build:
      context: ./WriterService
      dockerfile: Dockerfile
    
    stdin_open: true
    tty: true
    environment:
      WEBSITE_URL: http://finquest_api-prod